### PR TITLE
Support for Mc2Discord 4.x

### PR DESCRIPTION
**Pull request by DenisD3D**
This PR add support for Mc2Discord 4.x (large parts of the mod have been rewritten, introducing breaking changes)

P.S. I'm the author of Mc2Discord

### CODE REVIEW

**Comment by RedstoneDubstep** [comment]
Hello, thank you for your contribution! Please make sure that you don't rearrange imports unnecessarily in `Mc2DiscordCompat`. Also, from my testing the fake join/leave messages don't work in this PR and I couldn't figure out why, maybe you have a bit more expertise and could help me out?

**Comment by DenisD3D** [comment]
Mybad I missed something, Sorry for that!
As for the imports, I migrated the package from ml.denisd3d to fr.denisd3d to be the same as my web domain. So it require all import to be updated to reflect that

**Comment by RedstoneDubstep** [comment]
Modifying imports to fix compile errors is of course fine, with "unnecessary rearrangement" I mean e.g. moving the `java.util.Collections` import from the top to the bottom of the `import` block or removing the blank line after the `com.mojang.authlib.GameProfile` import.

**Comment by RedstoneDubstep** [comment]
Since the fake join/leave message error is fixed now, I'll merge this PR and fix the other formalities myself. Thank you very much!

**Pull request merged**
